export const SCENE_CONFIG = {
  waterlinePercent: 58,
  asset: {
    background: 'public/assets/pond-environment.png',
    puffer: 'public/assets/puffer.webp',
    snail: 'public/assets/snail.webp',
  },
  animals: [
    {
      id: 'puffer-buff',
      profile: 'mint-drift',
      type: 'puffer',
      left: 12,
      depth: 12,
      size: 12,
      duration: 19,
      delay: -4,
      swayX: 3.2,
      swayY: 1.0,
      spin: 4,
      flipped: false,
    },
    {
      id: 'puffer-peach',
      profile: 'sunset-skip',
      type: 'puffer',
      left: 31,
      depth: 18,
      size: 11,
      duration: 22,
      delay: -7,
      swayX: 2.3,
      swayY: 0.9,
      spin: -3.6,
      flipped: true,
    },
    {
      id: 'puffer-cobalt',
      profile: 'deep-dart',
      type: 'puffer',
      left: 58,
      depth: 22,
      size: 13,
      duration: 24,
      delay: -9,
      swayX: 2.9,
      swayY: 1.2,
      spin: 2.8,
      flipped: false,
    },
    {
      id: 'puffer-lime',
      profile: 'reed-hover',
      type: 'puffer',
      left: 43,
      depth: 42,
      size: 10,
      duration: 21,
      delay: -13,
      swayX: 2.1,
      swayY: 0.8,
      spin: -2.4,
      flipped: true,
    },
    {
      id: 'puffer-rose',
      profile: 'shell-peek',
      type: 'puffer',
      left: 84,
      depth: 28,
      size: 11,
      duration: 25,
      delay: -18,
      swayX: 2.5,
      swayY: 1.0,
      spin: 3.2,
      flipped: false,
    },
    {
      id: 'snail-amber',
      profile: 'stone-spiral',
      type: 'snail',
      left: 23,
      depth: 56,
      size: 9,
      duration: 32,
      delay: -11,
      swayX: 1.8,
      swayY: 0.35,
      spin: 0,
      flipped: false,
    },
    {
      id: 'snail-moss',
      profile: 'river-crawl',
      type: 'snail',
      left: 77,
      depth: 62,
      size: 10,
      duration: 37,
      delay: -16,
      swayX: 2.0,
      swayY: 0.25,
      spin: 0,
      flipped: true,
    },
  ],
};
